#!/usr/bin/env python3
"""Export BeeKeeper_GDD_Worksheet.docx to BeeKeeper_GDD_Worksheet.md.

The .docx is the document you edit; the .md is a generated, readable copy so
Claude sessions (and git diffs) can see the worksheet's text. Re-run after
every edit of the worksheet:

    python3 .claude/scripts/gdd-to-markdown.py

Standard library only. Output depends only on the .docx, so re-running on an
unchanged worksheet produces an identical file.
"""
import datetime
import os
import xml.etree.ElementTree as ET
import zipfile

W = '{http://schemas.openxmlformats.org/wordprocessingml/2006/main}'
ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..'))
SOURCE = os.path.join(ROOT, 'BeeKeeper_GDD_Worksheet.docx')
OUTPUT = os.path.join(ROOT, 'BeeKeeper_GDD_Worksheet.md')

HEADING_LEVELS = {'Title': '#', 'Heading1': '##', 'Heading2': '###', 'Heading3': '####'}


def run_text(element):
    parts = []
    for node in element.iter():
        if node.tag == W + 't':
            parts.append(node.text or '')
        elif node.tag == W + 'tab':
            parts.append(' ')
        elif node.tag in (W + 'br', W + 'cr'):
            parts.append('\n')
    return ''.join(parts)


def style_of(paragraph):
    style = paragraph.find(f'{W}pPr/{W}pStyle')
    return style.get(W + 'val') if style is not None else ''


def has_figure(paragraph):
    return any(True for _ in paragraph.iter(W + 'drawing'))


def cell_paragraphs(cell):
    return [run_text(p).strip() for p in cell.iter(W + 'p') if run_text(p).strip()]


def escape_cell(text):
    return text.replace('|', '\\|').replace('\n', '<br>')


def render_table(table):
    rows = []
    for row in table.findall(W + 'tr'):
        rows.append([cell_paragraphs(cell) for cell in row.findall(W + 'tc')])
    if not rows:
        return []

    # Single-cell tables are the worksheet's coloured boxes: render as quotes.
    if all(len(r) == 1 for r in rows):
        lines = []
        for r in rows:
            paragraphs = r[0] or ['(empty box)']
            for i, text in enumerate(paragraphs):
                if i:
                    lines.append('>')
                lines.append('> ' + text.replace('\n', '\n> '))
        return lines

    width = max(len(r) for r in rows)
    lines = []
    for index, r in enumerate(rows):
        cells = [escape_cell(' '.join(c)) for c in r]
        cells += [''] * (width - len(cells))
        lines.append('| ' + ' | '.join(cells) + ' |')
        if index == 0:
            lines.append('|' + '---|' * width)
    return lines


def main():
    archive = zipfile.ZipFile(SOURCE)
    body = ET.fromstring(archive.read('word/document.xml')).find(W + 'body')
    modified = datetime.date.fromtimestamp(os.path.getmtime(SOURCE)).isoformat()

    out = [
        '<!-- GENERATED from BeeKeeper_GDD_Worksheet.docx by .claude/scripts/gdd-to-markdown.py.',
        '     Do not edit this file: edit the .docx, then re-run the script. -->',
        '',
        f'*Generated copy of `BeeKeeper_GDD_Worksheet.docx` (worksheet last modified {modified}). '
        'Edit the .docx, not this file. Figures are left out; see the .docx.*',
        '',
    ]
    json_depth = 0

    for element in body:
        if element.tag == W + 'tbl':
            out.extend(render_table(element))
            out.append('')
            continue
        if element.tag != W + 'p':
            continue

        text = run_text(element)
        stripped = text.strip()

        # Appendix C is a JSON document typed as plain paragraphs: fence it.
        if json_depth == 0 and stripped == '{':
            out.append('```json')
        if json_depth > 0 or stripped == '{':
            out.append(text.rstrip())
            json_depth += text.count('{') - text.count('}')
            if json_depth <= 0:
                json_depth = 0
                out.extend(['```', ''])
            continue

        if not stripped:
            if has_figure(element):
                out.extend(['*[figure — see the .docx]*', ''])
            continue

        style = style_of(element)
        if style in HEADING_LEVELS:
            out.extend([f'{HEADING_LEVELS[style]} {" ".join(stripped.split())}', ''])
        elif style == 'ListParagraph':
            out.append('- ' + stripped.replace('\n', ' '))
        else:
            if out and out[-1].startswith('- '):
                out.append('')
            out.extend([stripped, ''])

    with open(OUTPUT, 'w', encoding='utf-8') as handle:
        handle.write('\n'.join(out).rstrip() + '\n')
    print(f'Wrote {os.path.relpath(OUTPUT, ROOT)} from {os.path.relpath(SOURCE, ROOT)}')


if __name__ == '__main__':
    main()
